apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./manifest/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: Employee-Application
