apiVersion: v1
kind: Secret
metadata:
  name: app-secrets  # Name of the Secret
  namespace: final         # Optional: Specify the namespace if not using "default"
type: Opaque                 # Type of Secret
data:
  DBUSER: cm9vdA==  # "root" base64-encoded
  DBPWD: cHc=       # "pw" base64-encoded
  AWS_ACCESS_KEY_ID: YWNjZXNzX2tleQ== # "access_key" base64-encoded
  AWS_SECRET_ACCESS_KEY: c2VjcmV0X2FjY2Vzc19rZXk= # "secret_access_key" base64-encoded
  AWS_SESSION_TOKEN: dG9rZW4= # "token" base64-encoded