apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: final
spec:
  ports:
  - port: 81
    targetPort: 81
  selector:
    tier: frontend
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: final
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: app-db
  type: ClusterIP
